server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: ATTENDANCE-SERVICE
            uri: lb://ATTENDANCE-SERVICE
            predicates:
              - Path=/api/attendance/**
          - id: PAYROLL-SERVICE
            uri: lb://PAYROLL-SERVICE
            predicates:
              - Path=/api/payroll/**
          - id: PERFORMANCE-REVIEW-SERVICE
            uri: lb://PERFORMANCE-REVIEW-SERVICE
            predicates:
              - Path=/api/performance-review/**
          - id: EMPLOYEE-SERVICE
            uri: lb://EMPLOYEE-SERVICE
            predicates:
              - Path=/api/**
